---
dependency:
  name: galaxy
driver:
  name: docker

provisioner:
  name: ansible
  inventory:
    group_vars:
      # some distributions need the openvswitch module loaded, and fail on
      # travis
      no_ovs_service:
        openvswitch_services: []

platforms:
  - name: ansible-ubuntu-lts
    image: ubuntu
    image_version: '16.04'
  - name: ansible-ubuntu-1704
    image: ubuntu
    image_version: '17.04'
  - name: ansible-debian
    image: debian
    image_version: 'latest'
  - name: ansible-arch
    image: archimg/base
    image_version: full
    command: /lib/systemd/systemd
    privileged: true
    groups:
      - no_ovs_service
  - name: ansible-fedora
    image: fedora
    image_version: latest
    command: /usr/lib/systemd/systemd
    privileged: true

scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8

# vim: set ts=2 sw=2:
